name: Terraform Lint and Plan

on:
  # Trigger workflow on pushes and pull requests
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform-lint-plan:
    name: Terraform Lint and Plan
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      # Run Terraform Format Check
      - name: Terraform Lint (Format Check)
        run: terraform fmt -check -recursive
        working-directory: ./tests

      # Validate Terraform configuration
      - name: Terraform Validate
        run: terraform validate
        working-directory: ./tests

      # Initialize Terraform
      - name: Terraform Init 
        run: terraform init
        working-directory: ./tests

      # Run Terraform Plan
      - name: Terraform Plan
        run: terraform plan
        working-directory: ./tests
