name: Terraform Lint and Plan

on:
  # Trigger workflow on pushes and pull requests
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform-lint-plan:
    name: Terraform Lint and Plan
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      # Initialize Terraform in root directory
      - name: Initialize Root Dir
        run: terraform init
        working-directory: ./

      # Validate Terraform configuration
      - name: Validate Module syntax
        run: terraform validate
        working-directory: ./


      # Initialize Terraform
      - name: Initialize Tests
        run: terraform init
        working-directory: ./tests

      # Validate Terraform configuration
      - name: Validate Tests Syntax
        run: terraform validate
        working-directory: ./tests
